//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamification.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class gamif_user
    {
        public string username { get; set; }
        public int peis_id { get; set; }
        public string user_avatar { get; set; }
    }
}
