//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamification.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GTAssignment
    {
        public decimal gtID { get; set; }
        public Nullable<decimal> gtExternalID { get; set; }
        public Nullable<decimal> gtTaskIntID { get; set; }
        public string gtResourceID { get; set; }
        public string gtProjectID { get; set; }
        public Nullable<System.DateTime> gtCurStartDate { get; set; }
        public Nullable<System.DateTime> gtCurFinishDate { get; set; }
        public Nullable<short> gtStatus { get; set; }
        public Nullable<short> gtIsDeleted { get; set; }
        public Nullable<decimal> gtETCHour { get; set; }
    }
}
