//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamification.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GTResource
    {
        public decimal gtID { get; set; }
        public string gtExternalID { get; set; }
        public string gtCategory { get; set; }
        public string gtName { get; set; }
        public Nullable<decimal> gtUnit { get; set; }
        public Nullable<short> gtCount { get; set; }
        public Nullable<System.DateTime> gtDOH { get; set; }
        public Nullable<System.DateTime> gtDOT { get; set; }
        public Nullable<short> gtIsRole { get; set; }
        public string gtUserText1 { get; set; }
        public string gtUserText2 { get; set; }
        public string gtUserText3 { get; set; }
        public string gtUserID { get; set; }
        public string gtUserPWD { get; set; }
        public Nullable<short> gtTeam { get; set; }
        public Nullable<short> gtTaskInsert { get; set; }
        public Nullable<short> gtTaskDelete { get; set; }
        public Nullable<short> gtTaskSplit { get; set; }
        public Nullable<short> gtTaskNotes { get; set; }
        public Nullable<short> gtNotInSource { get; set; }
        public byte[] gtAvail { get; set; }
        public string gtExtCode { get; set; }
        public Nullable<short> gtInProcess { get; set; }
        public Nullable<short> gtBOCCalendar { get; set; }
        public string gtEMail { get; set; }
        public string gtUnitLabel { get; set; }
        public Nullable<short> gtCheckOvercommit { get; set; }
        public Nullable<decimal> gtMaxUnitsWeek { get; set; }
        public string gtInstanceID { get; set; }
        public Nullable<short> gtIsAvailable { get; set; }
        public string gtCustomText1 { get; set; }
        public string gtCustomText2 { get; set; }
        public Nullable<decimal> gtCustomNumber1 { get; set; }
        public Nullable<decimal> gtCustomNumber2 { get; set; }
        public Nullable<System.DateTime> gtCustomDate1 { get; set; }
        public Nullable<System.DateTime> gtCustomDate2 { get; set; }
        public Nullable<short> gtCustomColor1 { get; set; }
        public Nullable<short> gtCustomColor2 { get; set; }
        public string gtCustomLV1 { get; set; }
        public string gtCustomLV2 { get; set; }
        public Nullable<decimal> gtLanguage { get; set; }
        public string gtOrganization { get; set; }
        public Nullable<short> gtEnableDownloadGuideline { get; set; }
        public Nullable<short> gtEnableDeleteInsertedTask { get; set; }
        public string gtCreatedUser { get; set; }
        public Nullable<System.DateTime> gtCreatedDate { get; set; }
        public string gtLockedBy { get; set; }
        public Nullable<System.DateTime> gtLockedByDate { get; set; }
        public string gtLastUpdateUser { get; set; }
        public Nullable<System.DateTime> gtLastUpdateDate { get; set; }
        public Nullable<short> gtEnableEditRisks { get; set; }
        public Nullable<short> gtEnableEditLessons { get; set; }
        public Nullable<short> gtEnableEditProblems { get; set; }
        public Nullable<short> gtEnableEditNews { get; set; }
        public Nullable<short> gtEnableDownloadForms { get; set; }
        public string gtProcessToUnlock { get; set; }
        public Nullable<short> gtEnableAddDoc { get; set; }
        public Nullable<short> gtEnableNews { get; set; }
        public Nullable<short> gtEnableViewDoc { get; set; }
        public Nullable<short> gtEnableKB { get; set; }
        public Nullable<short> gtEnableKBEdit { get; set; }
        public Nullable<short> gtTRLockEdit { get; set; }
        public Nullable<short> gtTREnableWBS { get; set; }
        public Nullable<short> gtTRMaxDailyActuals { get; set; }
        public Nullable<short> gtEnableEditProposed { get; set; }
        public Nullable<decimal> gtProcSiteID { get; set; }
        public Nullable<short> gtOverCommitted { get; set; }
        public string gtCustomLV3 { get; set; }
        public string gtCustomLV4 { get; set; }
        public Nullable<short> gtEnableViewProjDocs { get; set; }
        public Nullable<short> gtEnableApproveTR { get; set; }
        public Nullable<System.DateTime> gtLastConnectionDate { get; set; }
        public Nullable<short> gtPEISConnected { get; set; }
    }
}
