//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamification.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GTTimeEntry
    {
        public decimal gtID { get; set; }
        public Nullable<decimal> gtTimeSheetID { get; set; }
        public Nullable<decimal> gtAssignmentID { get; set; }
        public Nullable<decimal> gtActualDay1 { get; set; }
        public Nullable<decimal> gtActualDay2 { get; set; }
        public Nullable<decimal> gtActualDay3 { get; set; }
        public Nullable<decimal> gtActualDay4 { get; set; }
        public Nullable<decimal> gtActualDay5 { get; set; }
        public Nullable<decimal> gtActualDay6 { get; set; }
        public Nullable<decimal> gtActualDay7 { get; set; }
        public Nullable<decimal> gtActualWeek { get; set; }
        public Nullable<decimal> gtPlanDay1 { get; set; }
        public Nullable<decimal> gtPlanDay2 { get; set; }
        public Nullable<decimal> gtPlanDay3 { get; set; }
        public Nullable<decimal> gtPlanDay4 { get; set; }
        public Nullable<decimal> gtPlanDay5 { get; set; }
        public Nullable<decimal> gtPlanDay6 { get; set; }
        public Nullable<decimal> gtPlanDay7 { get; set; }
        public Nullable<decimal> gtPlanWeek { get; set; }
        public Nullable<decimal> gtPlanTask { get; set; }
        public string gtUserText1 { get; set; }
        public string gtUserText2 { get; set; }
        public string gtMngrComments { get; set; }
        public string gtUserComments { get; set; }
        public Nullable<decimal> gtProposedETC { get; set; }
        public string gtNotes { get; set; }
        public Nullable<short> gtHasNotes { get; set; }
        public Nullable<short> gtStatus { get; set; }
        public Nullable<decimal> gtPercentComplete { get; set; }
        public Nullable<short> gtInsertedTask { get; set; }
        public string gtAppUser { get; set; }
        public Nullable<System.DateTime> gtAppDate { get; set; }
        public string gtAdjUser { get; set; }
        public Nullable<System.DateTime> gtAdjDate { get; set; }
    }
}
