//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamification.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GTTimePeriod
    {
        public decimal gtID { get; set; }
        public Nullable<System.DateTime> gtStart { get; set; }
        public Nullable<System.DateTime> gtFinish { get; set; }
        public Nullable<short> gtStatus { get; set; }
        public Nullable<System.DateTime> gtStatusDate { get; set; }
        public string gtStatusBy { get; set; }
        public Nullable<short> gtIsOpen { get; set; }
        public Nullable<short> gtDoPopulate { get; set; }
        public Nullable<short> gtDoPost { get; set; }
        public string gtCreatedUser { get; set; }
        public Nullable<System.DateTime> gtCreatedDate { get; set; }
        public string gtLockedBy { get; set; }
        public Nullable<System.DateTime> gtLockedByDate { get; set; }
        public string gtLastUpdateUser { get; set; }
        public Nullable<System.DateTime> gtLastUpdateDate { get; set; }
        public Nullable<short> gtDoReplicate { get; set; }
    }
}
