//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gamification.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RCR
    {
        public string Tipo_RCR { get; set; }
        public string Categoria___Proceso___Rol { get; set; }
        public string Aplicación___Sub_Proceso___Sub_Rol__Aplicación___Sub_Proceso___Sub_Rol__Aplicación___Sub_Proceso___Sub_Rol { get; set; }
        public string Estado__Estado { get; set; }
        public string Solicitante { get; set; }
        public string Key_User { get; set; }
        public string BPO { get; set; }
        public string Número { get; set; }
        public string Concepto { get; set; }
        public string Controller { get; set; }
        public string Analista_FACT { get; set; }
        public Nullable<System.DateTime> Fechas_Generación { get; set; }
        public string Criticidad__Criticidad { get; set; }
        public string Complejidad { get; set; }
        public System.DateTime Fec_Hora_Inicio_Indicador_1__Acuse_de_Recibo__Controller_ { get; set; }
        public Nullable<System.DateTime> Fecha_Limite_Indicador_1__Fecha_Limite_Indicador_1 { get; set; }
        public Nullable<System.DateTime> Fec_Hora_Fin_Indicador_1__Acuse_de_Recibo { get; set; }
        public Nullable<System.DateTime> Fecha_Planificada_de_Inicio_Estudio_Factibilidad { get; set; }
        public Nullable<System.DateTime> Fecha_Planificada_de_Entrega_Estudio_Factibilidad__Ind_2_ { get; set; }
        public string Se_solicitó_mayor_información_a_solicitante { get; set; }
        public Nullable<System.DateTime> Fec_hora_envio_a_solicitante_para_información_adicional { get; set; }
        public Nullable<System.DateTime> Fec_hora_recepción_de_info_por_parte_del_solicitante { get; set; }
        public string Requiere_SF_ { get; set; }
        public Nullable<System.DateTime> Fec_hora_envio_a_SF_para_estimación { get; set; }
        public Nullable<System.DateTime> Fec_Hora_recepción_de_estimación_de_esfuerzo_SF { get; set; }
        public Nullable<System.DateTime> Fecha_de_entrega_Estudio_Factibilidad__Ind_2_ { get; set; }
        public Nullable<System.DateTime> Fecha_Planificada_de_Inicio_Mejora_Contínua { get; set; }
        public Nullable<System.DateTime> Fecha_Planificada_de_Entrega_Mejora_Contínua__Ind_3_ { get; set; }
        public string Analista_Mejora_Contínua__Analista_Mejora_Contínua__Analista_Mejora_Contínua { get; set; }
        public string C_Requiere_SF___Requiere_SF____Requiere_SF____Requiere_SF_ { get; set; }
        public Nullable<System.DateTime> Fec_Hora_entrega_Espec_Funcional__analista___Fec_Hora_entrega_Espec_Funcional__analista_ { get; set; }
        public Nullable<System.DateTime> Fec_Hora_Aprobación_EF__controller_ { get; set; }
        public Nullable<System.DateTime> Fec_hora_Aprobación_EF__Solicitante_ { get; set; }
        public Nullable<System.DateTime> Fec_hora_Documento_de_Pruebas__analista_ { get; set; }
        public Nullable<System.DateTime> Fec_hora_Revalidar_fecha_de_entrega__SF_ { get; set; }
        public Nullable<System.DateTime> Fecha_definitiva_de_Entrega_Mejora_Contínua__Ind_3_ { get; set; }
        public Nullable<System.DateTime> Fec_hora_ET__Analista_SF_ { get; set; }
        public Nullable<System.DateTime> Fec_hora_Desarrollo_y_Pruebas__SF_ { get; set; }
        public Nullable<System.DateTime> Fec_hora_Pruebas__Analista_ { get; set; }
        public Nullable<System.DateTime> Fec_hora_Pruebas__Usuario_ { get; set; }
        public Nullable<System.DateTime> Fec_hora_Gestión_Pase_a_Prod__Ind_3_ { get; set; }
        public Nullable<System.DateTime> Fec_hora_Pase_a_Prod__CSOPE_ { get; set; }
        public Nullable<System.DateTime> Fec_hora_capacitación_2 { get; set; }
    }
}
